version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vedra-pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vedra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: vedra-backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/vedra
      JWT_SECRET: dev-secret-change
      FRONTEND_ORIGIN: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      python -c 'from app.models import Base; from app.deps import engine; Base.metadata.create_all(engine); print(\"Tables created successfully!\")' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
