version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  search:
    image: opensearchproject/opensearch:2.3.0
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      cluster.name: invenio
      network.host: 0.0.0.0
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://search:9200/_cluster/health"]
      interval: 15s
      timeout: 5s
      retries: 20

  cache:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20

  web:
    image: python:3.11-slim
    depends_on:
      db: { condition: service_healthy }
      search: { condition: service_healthy }
      cache: { condition: service_healthy }
    environment:
      # DB
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # SEARCH
      OPENSEARCH_HOST: ${OPENSEARCH_HOST}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_PROTOCOL: ${OPENSEARCH_PROTOCOL}
      # CACHE/BROKER
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # SITE
      SECRET_KEY: ${INVENIO_SECRET_KEY}
      SITE_HOST: ${INVENIO_SITE_HOST}
    volumes:
      - ./invenio-vedra:/app/invenio-vedra:cached
      - ./auth_api.py:/app/auth_api.py:cached
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["sh", "-c", "pip install fastapi uvicorn psycopg2-binary email-validator && python auth_api.py"]

  worker:
    image: python:3.11-slim
    depends_on:
      db: { condition: service_healthy }
      search: { condition: service_healthy }
      cache: { condition: service_healthy }
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      OPENSEARCH_HOST: ${OPENSEARCH_HOST}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SECRET_KEY: ${INVENIO_SECRET_KEY}
    volumes:
      - ./invenio-vedra:/app/invenio-vedra:cached
    working_dir: /app
    command: ["python", "-c", "import time; print('Worker ready'); time.sleep(3600)"]
